insert into public.products (
  id,
  name,
  brand,
  description,
  price,
  old_price,
  category,
  image_url,
  in_stock,
  stock_quantity,
  is_featured,
  sort_order
) values
  (
    1,
    'Pineapple Pina Colada',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (АНАНАС ПИНА КОЛАДА)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/hTA3q3nEUkca6ITT7JBw.png',
    true,
    null,
    true,
    10
  ),
  (
    2,
    'Watermelon Cherry',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (АРБУЗ ВИШНЯ)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/3KQ7cR29WOL369maKzOI.png',
    true,
    null,
    true,
    20
  ),
  (
    3,
    'Blue Raspberry Lemonade',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (ГОЛУБАЯ МАЛИНА ЛИМОНАД)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/LcJM5BfxqvtR4RcmyjCr.png',
    true,
    null,
    false,
    30
  ),
  (
    4,
    'Grape',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (ВИНОГРАД)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/SSg42W4WBEnvXACAXnnI.png',
    true,
    null,
    false,
    40
  ),
  (
    5,
    'Cherry Cola',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (ВИШНЕВАЯ КОЛА)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/NMvD0fsjJwdaYaTVgp9p.png',
    true,
    null,
    false,
    50
  ),
  (
    6,
    'Cherry',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (ВИШНЯ)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/QbHs9z003qyavyB6fB4K.png',
    true,
    null,
    false,
    60
  ),
  (
    7,
    'Passion Fruit Guava',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (МАРАКУЙЯ ГУАВА)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/Hp2HWwEeOuWF2DgKzxwC.png',
    true,
    null,
    false,
    70
  ),
  (
    8,
    'Watermelon',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (АРБУЗ)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/8ch1vUfgTSJgSP67AJoE.png',
    true,
    null,
    false,
    80
  ),
  (
    9,
    'Pink Grapefruit',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (РОЗОВЫЙ ГРЕЙПФРУТ)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/oN4NH81tEPfJHLRjn1zd.png',
    true,
    null,
    false,
    90
  ),
  (
    10,
    'Pink Lemonade',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (РОЗОВЫЙ ЛИМОНАД)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/hq235pMVL1J8eMKfI6gv.png',
    true,
    null,
    false,
    100
  ),
  (
    11,
    'Blueberry',
    'ELF LIQ',
    'Солевая жидкость ELF LIQ 30мл 50мг (ЧЕРНИКА)',
    200,
    null,
    'Elf Liq',
    'https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/QUYVlmNW5BGGjTVDUFmt/pub/s5h6Ue5cEP12NKHrJ2nw.png',
    true,
    null,
    false,
    110
  )
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  description = excluded.description,
  price = excluded.price,
  old_price = excluded.old_price,
  category = excluded.category,
  image_url = excluded.image_url,
  in_stock = excluded.in_stock,
  stock_quantity = excluded.stock_quantity,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select max(id) from public.products), 1)
);
