create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  description text,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= 0),
  category text,
  image_url text,
  in_stock boolean not null default true,
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_in_stock_sort_idx
  on public.products (in_stock, sort_order, name);

create index if not exists products_category_idx
  on public.products (category);

create index if not exists products_featured_idx
  on public.products (is_featured);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;

create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();
